name: Build & Publish Container

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          push: true
          tags: ghcr.io/the127/keyline-ui:${{ github.ref_name }}

      - uses: sigstore/cosign-installer@v3

      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ghcr.io/the127/keyline-ui:${{ github.ref_name }}
          format: cosign-vuln
          output: vuln.json

      - name: Attest vulnerabilities
        run: |
          cosign attest --predicate vuln.json --type vuln --yes "ghcr.io/the127/keyline-ui:${{ github.ref_name }}"
